export const COMETCHAT_CONSTANTS = {
    NO_ITEM_SELECTED_MESSAGE: "Виберіть чат, щоб почати обмінюватися повідомленнями",//"Select a chat to start messaging",
    LOADING_MESSSAGE: "Завантаження...",
    ADDING_MESSSAGE: "Додавання...",
    CREATING_MESSSAGE: "Створення...",
    SEARCH_LOADING: "Пошук...",
    ERROR_LOADING_USERS: "Помилка завантаження користувачів",
    ERROR_LOADING_CHATS: "Помилка завантаження чатів",
    ERROR_COMETCHAT_LOGIN: "Log in error, reload",
    ERROR_NO_USERS_FOUND: "Користувачів не знайдено",
    EMPTY_STRING: "",
    SINGLE_SPACE: " ",
    USERS: "Користувачі",
    CHATS: "Розмови",
    GROUPS: "Групи",
    MORE: "More",
    MESSAGE_IMAGE: "📷 Image",
    MESSAGE_FILE: "📁 File",
    MESSAGE_VIDEO: "🎥 Video",
    MESSAGE_AUDIO: "🎵 Audio",
    CUSTOM_MESSAGE: "You have a message",
    CUSTOM_MESSAGE_DOCUMENT: "📃 Document",
    CUSTOM_MESSAGE_WHITEBOARD: "📝 Whiteboard",
    ONLINE: "Онлайн",
    OFFLINE: "Офлайн",
    ADMINISTRATOR: "Адміністратор",
    MODERATOR: "Модератор",
    PARTICIPANT: "Учасник",
    PUBLIC: "Публічна",
    PRIVATE: "Приватна",
    PASSWORD_PROTECTED: "Захищена паролем",
    PRIVACY_AND_SECURITY: "Privacy and Security",
    PREFERENCES: "Preferences",
    MEMBERS_COUNT: "Кількість учасників",
    MEMBERS: "Учасники",
    TODAY: "Сьогодні",
    YESTERDAY: "Вчора",
    TYPING: "typing...",
    IS_TYPING: "is typing...",
    CLOSE: "Закрити",
    ENTER_GROUP_NAME: "Введіть назву групи",
    ADD_MEMBERS: "Додати учасника",
    SEND_MESSAGE: "Надіслати повідомлення",
    UNBLOCK_USER: "Unblock User",
    BLOCK_USER: "Block User",
    DELETE_AND_EXIT: "Delete and Exit",
    LEAVE_GROUP: "Покинути групу",
    SHARED_MEDIA: "Спільні медіа",
    VIDEO_CALL: "Video call",
    AUDIO_CALL: "Audio call",
    REPLY: "reply",
    REPLIES: "replies",
    LAUNCH: "Launch",
    SHARED_COLLABORATIVE_DOCUMENT: "has shared a collaborative document",
    SHARED_COLLABORATIVE_WHITEBOARD: "has shared a collaborative whiteboard",
    CREATED_WHITEBOARD: "You’ve created a new collaborative whiteboard",
    CREATED_DOCUMENT: "You’ve created a new collaborative document",
    PHOTOS: "Фото",
    VIDEOS: "Відео",
    DOCUMENT: "Документи",
    YOU_DELETED_THIS_MESSAGE: "⚠️ Ви видалили це повідомлення",
    THIS_MESSAGE_DELETED: "⚠️ Це повідомлення видалено",
    VIEW_ON_YOUTUBE: "View on Youtube",
    SEARCH: "Пошук",
    NO_USERS_FOUND: "Користувача не знайдено",
    ERROR: "Помилка",
    NO_GROUPS_FOUND: "Груп не знайдено",
    NO_CHATS_FOUND: "Не знайдено чатів",
    MEDIA_MESSAGE: "Media message",
    JOINED: "joined",
    ADD: "Додати",
    NO_BANNED_MEMBERS_FOUND: "Учасників не знайдено",
    BANNED_MEMBERS: "Banned Members",
    NAME: "Користувач",
    SCOPE: "Роль",
    UNBAN: "Розблокувати",
    SELECT_GROUP_TYPE: "Виберіть тип групи",
    ENTER_GROUP_PASSWORD: "Введіть пароль групи",
    CREATE: "Створити",
    CREATE_GROUP: "Створити групу",
    ENTER_YOUR_QUESTION: "Enter your question",
    OPTIONS: "Опції",
    ENTER_YOUR_OPTION: "Enter your option",
    ADD_NEW_OPTION: "Add new option",
    VIEW_MEMBERS: "Переглянути учасників",
    DETAILS: "Деталі",
    NOTIFICATIONS: "Сповіщення",
    OTHER: "Інше",
    HELP: "Допомога",
    REPORT_PROBLEM: "Повідомити про проблему",
    GROUP_MEMBERS: "Учасники",
    BAN: "Блокувати",
    KICK: "Вилучити",
    PRIVATE_GROUP: "Приватна група",
    PROTECTED_GROUP: "Захищена група",
    VISIT: "Visit",
    ATTACH: "Attach",
    ATTACH_FILE: "Attach file",
    ATTACH_VIDEO: "Attach video",
    ATTACH_AUDIO: "Attach audio",
    ATTACH_IMAGE: "Attach image",
    COLLABORATE_USING_DOCUMENT: "Collaborate using a document",
    COLLABORATE_USING_WHITEBOARD: "Collaborate using a whiteboard",
    ADD_EMOJI: "Add Emoji",
    EMOJI: "Emoji",
    ENTER_YOUR_MESSAGE_HERE: "Введіть своє повідомлення",
    NO_MESSAGES_FOUND: "Немає повідомлень",
    THREAD: "Thread",
    COLLABORATIVE_DOCUMENT: "Collaborative Document",
    COLLABORATIVE_WHITEBOARD: "Collaborative Whiteboard",
    ADD_REACTION: "Add reaction",
    HEART: "heart",
    NO_STICKERS_FOUND: "No stickers found",
    REPLY_TO_THREAD: "Reply to thread",
    REPLY_IN_THREAD: "Reply in thread",
    DELETE_MESSAGE: "Видалити повідомлення",
    EDIT_MESSAGE: "Редагувати повідомлення",
    SUNDAY: "Неділя",
    MONDAY: "Понеділок",
    TUESDAY: "Вівторок",
    WEDNESDAY: "Середа",
    THURSDAY: "Четвер",
    FRIDAY: "П'ятниця",
    SATURDAY: "Субота",
    GROUP_NAME_BLANK: "Назва групи не має бути пустою",
    GROUP_TYPE_BLANK: "Тип групи не можу бути пустим",
    GROUP_PASSWORD_BLANK: "Пароль групи не може бути пустим",
    POLL_QUESTION_BLANK: "Question cannot be blank",
    POLL_OPTION_BLANK: "Option cannot be blank",
    OWNER: "Власник",
    CUSTOM_MESSAGE_LOCATION: "📍Location",
    YOU: "You",
    PRIVACY: "Privacy",
    BLOCKED_USERS: "Blocked Users",
    "YOU'VE_BLOCKED": "You've blocked",
    NO_PHOTOS: "Немає фото",
    NO_VIDEOS: "Немає відео",
    NO_DOCUMENTS: "Немає документів",
    NO_RECORDS_FOUND: "No records found.",
    JOIN: "Join",
    SENT: "sent",
    DELIVERED: "deliv",
    ENTER_YOUR_PASSWORD: "Введіть пароль",
    LAST_ACTIVE_AT: "Last Active At: ",
    REACTED: "reacted",
  };
  